/**	
	PROGRAM NAME:		19ai. Construct curves
	PRIMARY PROGRAMMER:	Marzan Khan

	LAST MODIFIED:		February 23, 2023

	GENERAL PURPOSE:	
		1) Create CI curves with overall weights using proc sgpanel

**/


*Contains all the datasets required by the hdPS macro;
libname cov "P:\sfmob\shared\Data\Covariates_nbz targettrial";

*All the datasets generated by the hdPS macro will be saved in the output library;
libname output "P:\sfmob\shared\Data\Non-bz TT subsets";


*Contains the TT input datasets;
libname target_i "P:\sfmob\mak\Data\target_master_9.19.2022";

*Contains the TT output datasets;
libname target_o "P:\sfmob\shared\Data\Non-BZ hypnotic Target Trial output datasets";

*Read the program containing formats;
%include "P:\sfmob\shared\Code\General Data Management\Create NJ-SHO and other user-defined formats 2022_10_21.sas" ;

ods graphics on ;

options mprint;

/*proc freq data=cov.estimates_overallweights;*/
/*	tables  combo_ipw_itt;*/
/*run;*/

data stack;
length group $40;
	set cov.cuminc_ppe_wt(in=a rename=daysto_censor_ppe=daysto_censor_itt) cov.cuminc_itt_wt(in=b);
	o_ppe=a;
	o_itt=b;


	if o_ppe=1 then group="Per-protocol";
	else if o_itt=1 then group="Intention-to-treat";




run;

/*proc print data=stack;*/
/*	where ppe=1 and daysto_censor_itt=71;*/
/*run;*/
/**/
/*proc freq data=stack;*/
/*	tables daysto_censor_itt;*/
/*	where ppe=1;*/
/*run;*/
*day 71 in the PPE exposure=0 not for exposure=1; *day 71 missing in ppe=1 for exposure =1;


options nodate nonumber;

ods pdf file='P:\sfmob\mak\Output\Working\Target trial output\Final analyses\Cumulative incidence curves.pdf'  dpi=300 ;
proc sgpanel data=stack  noautolegend ;
  /* Use the SORT= option to order the panels */
  panelby group /   novarname rows=1 columns=2  HEADERATTRS=(Color=Black Family='Times New Roman' Size=12 
        /*Style=Italic Weight=Bold*/);
/*styleattrs  datacontrastcolors=( red);*/
  series x = daysto_censor_itt y = cum_inc_percent / group=exposure    ;
 	 band x=daysto_censor_itt  lower=p_lb_percent upper=p_ub_percent /  group=exposure transparency=0.7  ;
rowaxis  label = 'Cumulaive Incidence (%)' LABELATTRS=(family="Times New Roman" size=12) VALUEATTRS=( Family='Times New Roman' size=12) ;
  colaxis label = 'Days' LABELATTRS=(family="Times New Roman" size=12)  values = (0 to 84 by 7) VALUEATTRS=( Family='Times New Roman' size=12 );
/*  keylegend;*/
run;

ods pdf close;
